"""initial_migration_all_tables

Revision ID: 08650b7f076b
Revises: 
Create Date: 2026-01-02 16:51:12.783148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08650b7f076b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('case_short_name', sa.String(), nullable=True),
    sa.Column('case_full_name', sa.String(), nullable=True),
    sa.Column('case_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('trial_date', sa.DateTime(), nullable=True),
    sa.Column('case_no', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.Integer(), nullable=True),
    sa.Column('case_status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_case_no'), 'cases', ['case_no'], unique=True)
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_table('users',
    sa.Column('user_no', sa.Integer(), nullable=False, unique=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('login_name', sa.String(), nullable=True),
    sa.Column('login_password', sa.LargeBinary(), nullable=True),
    sa.Column('require_password_change', sa.Boolean(), nullable=True),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_no'), 'users', ['user_no'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_login_name'), 'users', ['login_name'], unique=True)
    op.create_table('jobs',
    sa.Column('job_date', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('timezone_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('case_no', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=255), nullable=True),
    sa.Column('scheduled_by_email', sa.String(length=255), nullable=True),
    sa.Column('job_loc_name', sa.String(length=255), nullable=True),
    sa.Column('job_loc_address', sa.String(length=255), nullable=True),
    sa.Column('job_loc_city', sa.String(length=255), nullable=True),
    sa.Column('job_loc_state', sa.String(length=255), nullable=True),
    sa.Column('job_loc_zip', sa.String(length=255), nullable=True),
    sa.Column('scheduling_notes_html', sa.String(), nullable=True),
    sa.Column('zoom_meeting_id', sa.BigInteger(), nullable=True),
    sa.Column('confirmation_notes_html', sa.String(), nullable=True),
    sa.Column('cancel_by', sa.Integer(), nullable=True),
    sa.Column('cancel_date', sa.DateTime(), nullable=True),
    sa.Column('job_no', sa.Integer(), nullable=True),
    sa.Column('cancel_details', sa.Text(), nullable=True),
    sa.Column('cancel_reason', postgresql.ENUM('HEARING_RESCHEDULED', 'WITNESS_ABSENT', 'ATTORNEY_ABSENT', 'JUDGE_ABSENT', name='cancel_reason_enum'), nullable=True),
    sa.Column('computed_status', sa.String(length=50), nullable=True),
    sa.Column('actual_session_start_time', sa.DateTime(), nullable=True),
    sa.Column('actual_session_end_time', sa.DateTime(), nullable=True),
    sa.Column('session_duration', sa.String(length=255), nullable=True),
    sa.Column('session_completed', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('video_upload_deadline', sa.DateTime(), nullable=True),
    sa.Column('expected_video_count', sa.Integer(), nullable=True),
    sa.Column('mark_is_done_case', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('mark_is_done_witnesses', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('mark_is_done_attorneys', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('mark_is_done_billings', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('mark_is_done_equipment_time', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['case_no'], ['cases.case_no'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_no')
    )
    op.create_index(op.f('ix_jobs_case_no'), 'jobs', ['case_no'], unique=False)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_table('attorneys',
    sa.Column('job_no', sa.Integer(), nullable=False),
    sa.Column('attorney_name', sa.String(length=255), nullable=False),
    sa.Column('firm_name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('order_details', sa.Text(), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('file_name_path', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['job_no'], ['jobs.job_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attorneys_id'), 'attorneys', ['id'], unique=False)
    op.create_index(op.f('ix_attorneys_job_no'), 'attorneys', ['job_no'], unique=False)
    op.create_table('billings',
    sa.Column('job_no', sa.Integer(), nullable=False),
    sa.Column('cancel_en_route', sa.Boolean(), nullable=True),
    sa.Column('cancel_setup', sa.Boolean(), nullable=True),
    sa.Column('billing_notes', sa.Text(), nullable=True),
    sa.Column('videographer_hours_present', sa.String(length=255), nullable=True),
    sa.Column('file_hours_length', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['job_no'], ['jobs.job_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billings_id'), 'billings', ['id'], unique=False)
    op.create_index(op.f('ix_billings_job_no'), 'billings', ['job_no'], unique=False)
    op.create_table('equipment_time',
    sa.Column('job_no', sa.Integer(), nullable=False),
    sa.Column('laptop_used', sa.Boolean(), nullable=True),
    sa.Column('pip_used', sa.Boolean(), nullable=True),
    sa.Column('exhibit_tech', sa.Boolean(), nullable=True),
    sa.Column('parking_cost', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=True),
    sa.Column('time_after', sa.Time(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['job_no'], ['jobs.job_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_time_id'), 'equipment_time', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_time_job_no'), 'equipment_time', ['job_no'], unique=False)
    op.create_table('job_assignments',
    sa.Column('assigner_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=False),
    sa.Column('job_no', sa.Integer(), nullable=False),
    sa.Column('case_no', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_no'], ['cases.case_no'], ),
    sa.ForeignKeyConstraint(['job_no'], ['jobs.job_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_assignments_id'), 'job_assignments', ['id'], unique=False)
    op.create_table('witnesses',
    sa.Column('job_no', sa.Integer(), nullable=False),
    sa.Column('witness_name', sa.String(length=255), nullable=False),
    sa.Column('witness_email', sa.String(length=255), nullable=True),
    sa.Column('actual_start_time', sa.Time(), nullable=True),
    sa.Column('actual_end_time', sa.Time(), nullable=True),
    sa.Column('read_sign_date', sa.DateTime(), nullable=True),
    sa.Column('read_sign_to', sa.Integer(), nullable=True),
    sa.Column('wit_no', sa.Integer(), nullable=True),
    sa.Column('read_on_text', sa.Text(), nullable=True),
    sa.Column('read_on_time', sa.Time(), nullable=True),
    sa.Column('read_off_text', sa.Text(), nullable=True),
    sa.Column('read_off_time', sa.Time(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['job_no'], ['jobs.job_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_witnesses_id'), 'witnesses', ['id'], unique=False)
    op.create_index(op.f('ix_witnesses_job_no'), 'witnesses', ['job_no'], unique=False)
    op.create_table('additional_documents',
    sa.Column('job_no', sa.Integer(), nullable=False),
    sa.Column('billing_id', sa.Integer(), nullable=True),
    sa.Column('equipment_time_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['billing_id'], ['billings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipment_time_id'], ['equipment_time.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_no'], ['jobs.job_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_additional_documents_billing_id'), 'additional_documents', ['billing_id'], unique=False)
    op.create_index(op.f('ix_additional_documents_equipment_time_id'), 'additional_documents', ['equipment_time_id'], unique=False)
    op.create_index(op.f('ix_additional_documents_id'), 'additional_documents', ['id'], unique=False)
    op.create_index(op.f('ix_additional_documents_job_no'), 'additional_documents', ['job_no'], unique=False)
    op.create_table('witness_videos',
    sa.Column('wit_no', sa.Integer(), nullable=False),
    sa.Column('job_no', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['job_no'], ['jobs.job_no'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wit_no'], ['witnesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_witness_videos_id'), 'witness_videos', ['id'], unique=False)
    op.create_index(op.f('ix_witness_videos_job_no'), 'witness_videos', ['job_no'], unique=False)
    op.create_index(op.f('ix_witness_videos_wit_no'), 'witness_videos', ['wit_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_witness_videos_wit_no'), table_name='witness_videos')
    op.drop_index(op.f('ix_witness_videos_job_no'), table_name='witness_videos')
    op.drop_index(op.f('ix_witness_videos_id'), table_name='witness_videos')
    op.drop_table('witness_videos')
    op.drop_index(op.f('ix_additional_documents_job_no'), table_name='additional_documents')
    op.drop_index(op.f('ix_additional_documents_id'), table_name='additional_documents')
    op.drop_index(op.f('ix_additional_documents_equipment_time_id'), table_name='additional_documents')
    op.drop_index(op.f('ix_additional_documents_billing_id'), table_name='additional_documents')
    op.drop_table('additional_documents')
    op.drop_index(op.f('ix_witnesses_job_no'), table_name='witnesses')
    op.drop_index(op.f('ix_witnesses_id'), table_name='witnesses')
    op.drop_table('witnesses')
    op.drop_index(op.f('ix_job_assignments_id'), table_name='job_assignments')
    op.drop_table('job_assignments')
    op.drop_index(op.f('ix_equipment_time_job_no'), table_name='equipment_time')
    op.drop_index(op.f('ix_equipment_time_id'), table_name='equipment_time')
    op.drop_table('equipment_time')
    op.drop_index(op.f('ix_billings_job_no'), table_name='billings')
    op.drop_index(op.f('ix_billings_id'), table_name='billings')
    op.drop_table('billings')
    op.drop_index(op.f('ix_attorneys_job_no'), table_name='attorneys')
    op.drop_index(op.f('ix_attorneys_id'), table_name='attorneys')
    op.drop_table('attorneys')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_case_no'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_login_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_no'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
