"""add new columns to jobs/cases/...

Revision ID: 08fc0055c50b
Revises: 6cfdf52b9ec4
Create Date: 2025-12-01 20:33:03.336846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08fc0055c50b'
down_revision: Union[str, Sequence[str], None] = '6cfdf52b9ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    cancel_reason_enum = postgresql.ENUM(
        'HEARING_RESCHEDULED',
        'WITNESS_ABSENT',
        'ATTORNEY_ABSENT',
        'JUDGE_ABSENT',
        name='cancel_reason_enum',
    )
    cancel_reason_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('cases', sa.Column('case_no', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('job_no', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('cancel_details', sa.Text(), nullable=True))
    op.add_column(
        'jobs',
        sa.Column(
            'cancel_resone',
            cancel_reason_enum,
            nullable=True,
        ),
    )
    op.add_column('witnesses', sa.Column('wit_no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('witnesses', 'wit_no')
    op.drop_column('jobs', 'cancel_resone')
    op.drop_column('jobs', 'cancel_details')
    op.drop_column('jobs', 'job_no')
    op.drop_column('cases', 'case_no')

    cancel_reason_enum = postgresql.ENUM(
        'HEARING_RESCHEDULED',
        'WITNESS_ABSENT',
        'ATTORNEY_ABSENT',
        'JUDGE_ABSENT',
        name='cancel_reason_enum',
    )
    cancel_reason_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
