"""Add computed_status column to jobs table

Revision ID: 14736fd12024
Revises: 08fc0055c50b
Create Date: 2025-12-03 15:49:57.680191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14736fd12024'
down_revision: Union[str, Sequence[str], None] = '08fc0055c50b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create ENUM type first
    job_status_enum = postgresql.ENUM('UPCOMING', 'SESSION_NOT_STARTED', 'SESSION_IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='job_status_enum', create_type=True)
    job_status_enum.create(op.get_bind(), checkfirst=True)
    
    # Add column
    op.add_column('jobs', sa.Column('computed_status', job_status_enum, nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'computed_status')
    # ### end Alembic commands ###
