"""add new tables

Revision ID: 6cfdf52b9ec4
Revises: 0e1a1bbf4c0b
Create Date: 2025-11-27 17:03:52.788108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cfdf52b9ec4'
down_revision: Union[str, Sequence[str], None] = '0e1a1bbf4c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('case_short_name', sa.String(), nullable=True),
    sa.Column('case_full_name', sa.String(), nullable=True),
    sa.Column('case_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('trial_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_table('jobs',
    sa.Column('job_date', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('timezone_no', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('case_no', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=255), nullable=True),
    sa.Column('scheduled_by_email', sa.String(length=255), nullable=True),
    sa.Column('job_loc_name', sa.String(length=255), nullable=True),
    sa.Column('job_loc_address', sa.String(length=255), nullable=True),
    sa.Column('job_loc_city', sa.String(length=255), nullable=True),
    sa.Column('job_loc_state', sa.String(length=255), nullable=True),
    sa.Column('job_loc_zip', sa.String(length=255), nullable=True),
    sa.Column('scheduling_notes_html', sa.String(), nullable=True),
    sa.Column('zoom_meeting_id', sa.BigInteger(), nullable=True),
    sa.Column('confirmation_notes_html', sa.String(), nullable=True),
    sa.Column('cancel_by', sa.Integer(), nullable=True),
    sa.Column('cancel_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_table('repositories',
    sa.Column('wit_no', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('repository_level', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('job_no', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_id'), 'repositories', ['id'], unique=False)
    op.create_table('witnesses',
    sa.Column('jod_no', sa.Integer(), nullable=False),
    sa.Column('witness_name', sa.String(length=255), nullable=False),
    sa.Column('witness_email', sa.String(length=255), nullable=True),
    sa.Column('actual_start_time', sa.Time(), nullable=True),
    sa.Column('actual_end_time', sa.Time(), nullable=True),
    sa.Column('read_sign_date', sa.DateTime(), nullable=True),
    sa.Column('read_sign_to', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_witnesses_id'), 'witnesses', ['id'], unique=False)
    op.alter_column('users', 'require_password_change',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'require_password_change',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_witnesses_id'), table_name='witnesses')
    op.drop_table('witnesses')
    op.drop_index(op.f('ix_repositories_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
