"""add witness_videos and other new modules

Revision ID: 7dd616281142
Revises: 95a7c2829173
Create Date: 2025-12-05 16:26:47.879423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd616281142'
down_revision: Union[str, Sequence[str], None] = '95a7c2829173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, add unique constraint on jobs.job_no to allow foreign key references
    op.create_unique_constraint('uq_jobs_job_no', 'jobs', ['job_no'])
    
    op.create_table('attorneys',
    sa.Column('job_no', sa.Integer(), nullable=False),
    sa.Column('attorney_name', sa.String(length=255), nullable=False),
    sa.Column('firm_name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('order_details', sa.Text(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('file_name_path', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['job_no'], ['jobs.job_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attorneys_id'), 'attorneys', ['id'], unique=False)
    op.create_index(op.f('ix_attorneys_job_no'), 'attorneys', ['job_no'], unique=False)
    op.create_table('billings',
    sa.Column('job_no', sa.Integer(), nullable=False),
    sa.Column('cancel_en_route', sa.Boolean(), nullable=True),
    sa.Column('cancel_setup', sa.Boolean(), nullable=True),
    sa.Column('billing_notes', sa.Text(), nullable=True),
    sa.Column('videographer_hours_present', sa.Time(), nullable=True),
    sa.Column('file_hours_length', sa.Time(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['job_no'], ['jobs.job_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billings_id'), 'billings', ['id'], unique=False)
    op.create_index(op.f('ix_billings_job_no'), 'billings', ['job_no'], unique=False)
    op.create_table('equipment_time',
    sa.Column('job_no', sa.Integer(), nullable=False),
    sa.Column('laptop_used', sa.Boolean(), nullable=True),
    sa.Column('pip_used', sa.Boolean(), nullable=True),
    sa.Column('exhibit_tech', sa.Boolean(), nullable=True),
    sa.Column('parking_cost', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=True),
    sa.Column('time_after', sa.Time(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['job_no'], ['jobs.job_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_time_id'), 'equipment_time', ['id'], unique=False)
    op.create_index(op.f('ix_equipment_time_job_no'), 'equipment_time', ['job_no'], unique=False)
    op.create_table('additional_documents',
    sa.Column('job_no', sa.Integer(), nullable=False),
    sa.Column('billing_id', sa.Integer(), nullable=True),
    sa.Column('equipment_time_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['billing_id'], ['billings.id'], ),
    sa.ForeignKeyConstraint(['equipment_time_id'], ['equipment_time.id'], ),
    sa.ForeignKeyConstraint(['job_no'], ['jobs.job_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_additional_documents_billing_id'), 'additional_documents', ['billing_id'], unique=False)
    op.create_index(op.f('ix_additional_documents_equipment_time_id'), 'additional_documents', ['equipment_time_id'], unique=False)
    op.create_index(op.f('ix_additional_documents_id'), 'additional_documents', ['id'], unique=False)
    op.create_index(op.f('ix_additional_documents_job_no'), 'additional_documents', ['job_no'], unique=False)
    op.create_table('witness_videos',
    sa.Column('wit_no', sa.Integer(), nullable=False),
    sa.Column('job_no', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['job_no'], ['jobs.job_no'], ),
    sa.ForeignKeyConstraint(['wit_no'], ['witnesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_witness_videos_id'), 'witness_videos', ['id'], unique=False)
    op.add_column('cases', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=True))
    # Note: Keeping uq_cases_case_no constraint as it's needed for foreign key
    op.add_column('jobs', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('repositories', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('users', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=True))
    # Add job_no as nullable first, copy data from jod_no, then make it NOT NULL
    op.add_column('witnesses', sa.Column('job_no', sa.Integer(), nullable=True))
    # Copy data from jod_no to job_no
    op.execute("UPDATE witnesses SET job_no = jod_no WHERE jod_no IS NOT NULL")
    # Now make it NOT NULL
    op.alter_column('witnesses', 'job_no', nullable=False)
    
    # Add text columns with defaults for existing rows
    op.add_column('witnesses', sa.Column('read_on_text', sa.Text(), nullable=True))
    op.add_column('witnesses', sa.Column('read_off_text', sa.Text(), nullable=True))
    op.execute("UPDATE witnesses SET read_on_text = '' WHERE read_on_text IS NULL")
    op.execute("UPDATE witnesses SET read_off_text = '' WHERE read_off_text IS NULL")
    op.alter_column('witnesses', 'read_on_text', nullable=False, server_default='')
    op.alter_column('witnesses', 'read_off_text', nullable=False, server_default='')
    
    # Add time columns - need to provide default for existing rows
    op.add_column('witnesses', sa.Column('read_on_time', sa.Time(), nullable=True))
    op.add_column('witnesses', sa.Column('read_off_time', sa.Time(), nullable=True))
    op.execute("UPDATE witnesses SET read_on_time = '00:00:00'::time WHERE read_on_time IS NULL")
    op.execute("UPDATE witnesses SET read_off_time = '00:00:00'::time WHERE read_off_time IS NULL")
    op.alter_column('witnesses', 'read_on_time', nullable=False)
    op.alter_column('witnesses', 'read_off_time', nullable=False)
    op.add_column('witnesses', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=True))
    op.create_unique_constraint(None, 'witnesses', ['wit_no'])
    op.create_foreign_key(None, 'witnesses', 'jobs', ['job_no'], ['job_no'], ondelete='CASCADE')
    op.drop_column('witnesses', 'jod_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('witnesses', sa.Column('jod_no', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'witnesses', type_='foreignkey')
    op.drop_constraint(None, 'witnesses', type_='unique')
    op.drop_column('witnesses', 'is_archived')
    op.drop_column('witnesses', 'read_off_time')
    op.drop_column('witnesses', 'read_off_text')
    op.drop_column('witnesses', 'read_on_time')
    op.drop_column('witnesses', 'read_on_text')
    op.drop_column('witnesses', 'job_no')
    op.drop_column('users', 'is_archived')
    op.drop_column('repositories', 'is_archived')
    op.drop_column('jobs', 'is_archived')
    # Note: uq_cases_case_no constraint already exists, no need to recreate
    op.drop_column('cases', 'is_archived')
    op.drop_index(op.f('ix_witness_videos_id'), table_name='witness_videos')
    op.drop_table('witness_videos')
    op.drop_index(op.f('ix_additional_documents_job_no'), table_name='additional_documents')
    op.drop_index(op.f('ix_additional_documents_id'), table_name='additional_documents')
    op.drop_index(op.f('ix_additional_documents_equipment_time_id'), table_name='additional_documents')
    op.drop_index(op.f('ix_additional_documents_billing_id'), table_name='additional_documents')
    op.drop_table('additional_documents')
    op.drop_index(op.f('ix_equipment_time_job_no'), table_name='equipment_time')
    op.drop_index(op.f('ix_equipment_time_id'), table_name='equipment_time')
    op.drop_table('equipment_time')
    op.drop_index(op.f('ix_billings_job_no'), table_name='billings')
    op.drop_index(op.f('ix_billings_id'), table_name='billings')
    op.drop_table('billings')
    op.drop_index(op.f('ix_attorneys_job_no'), table_name='attorneys')
    op.drop_index(op.f('ix_attorneys_id'), table_name='attorneys')
    op.drop_table('attorneys')
    # Drop unique constraint on jobs.job_no
    op.drop_constraint('uq_jobs_job_no', 'jobs', type_='unique')
    # ### end Alembic commands ###
