"""add_job_assignments_table

Revision ID: 8c8b2543a31f
Revises: c111e51e4459
Create Date: 2025-12-30 15:31:50.547316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c8b2543a31f'
down_revision: Union[str, Sequence[str], None] = 'c111e51e4459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_assignments',
    sa.Column('assigner_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=False),
    sa.Column('job_no', sa.Integer(), nullable=False),
    sa.Column('case_no', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entered_at', sa.DateTime(), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_no'], ['cases.case_no'], ),
    sa.ForeignKeyConstraint(['job_no'], ['jobs.job_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_assignments_id'), 'job_assignments', ['id'], unique=False)
    # Removed: op.drop_constraint(op.f('uq_cases_case_no'), 'cases', type_='unique')
    # The unique constraint on cases.case_no should remain as it's needed for foreign keys
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_assignments_id'), table_name='job_assignments')
    op.drop_table('job_assignments')
    # ### end Alembic commands ###
