"""change computed_status from enum to string

Revision ID: 8d69123adec6
Revises: 14736fd12024
Create Date: 2025-12-03 16:34:04.114578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d69123adec6'
down_revision: Union[str, Sequence[str], None] = '14736fd12024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'computed_status',
               existing_type=postgresql.ENUM('UPCOMING', 'SESSION_NOT_STARTED', 'SESSION_IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='job_status_enum'),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'computed_status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('UPCOMING', 'SESSION_NOT_STARTED', 'SESSION_IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='job_status_enum'),
               existing_nullable=True)
    # ### end Alembic commands ###
