"""add_mark_is_done_columns_to_jobs

Revision ID: d9389febbc55
Revises: b7a33a0e2d49
Create Date: 2025-12-29 14:02:09.890296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9389febbc55'
down_revision: Union[str, Sequence[str], None] = 'b7a33a0e2d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraint first before modifying unique constraint
    op.drop_constraint('jobs_case_no_fkey', 'jobs', type_='foreignkey')
    # Drop and recreate unique constraint (matching original definition)
    op.drop_constraint(op.f('uq_cases_case_no'), 'cases', type_='unique')
    op.create_unique_constraint(op.f('uq_cases_case_no'), 'cases', ['case_no'])
    # Recreate foreign key constraint
    op.create_foreign_key('jobs_case_no_fkey', 'jobs', 'cases', ['case_no'], ['case_no'])
    
    # Convert VARCHAR to TIME using USING clause
    # Handle NULL and empty strings, then cast valid time strings
    op.execute("""
        ALTER TABLE equipment_time 
        ALTER COLUMN time_after 
        TYPE TIME WITHOUT TIME ZONE 
        USING CASE 
            WHEN time_after IS NULL OR TRIM(time_after) = '' THEN NULL
            ELSE time_after::TIME WITHOUT TIME ZONE
        END
    """)
    op.add_column('jobs', sa.Column('mark_is_done_case', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('mark_is_done_witnesses', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('mark_is_done_attorneys', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('mark_is_done_billings', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('mark_is_done_equipment_time', sa.Boolean(), nullable=True))
    
    # Drop foreign key constraints that depend on uq_jobs_job_no
    op.drop_constraint('attorneys_job_no_fkey', 'attorneys', type_='foreignkey')
    op.drop_constraint('billings_job_no_fkey', 'billings', type_='foreignkey')
    op.drop_constraint('equipment_time_job_no_fkey', 'equipment_time', type_='foreignkey')
    op.drop_constraint('additional_documents_job_no_fkey', 'additional_documents', type_='foreignkey')
    op.drop_constraint('witness_videos_job_no_fkey', 'witness_videos', type_='foreignkey')
    op.drop_constraint('witnesses_job_no_fkey', 'witnesses', type_='foreignkey')
    
    # Drop and recreate unique constraint
    op.drop_constraint(op.f('uq_jobs_job_no'), 'jobs', type_='unique')
    op.create_unique_constraint(op.f('uq_jobs_job_no'), 'jobs', ['job_no'])
    
    # Recreate foreign key constraints
    op.create_foreign_key('attorneys_job_no_fkey', 'attorneys', 'jobs', ['job_no'], ['job_no'])
    op.create_foreign_key('billings_job_no_fkey', 'billings', 'jobs', ['job_no'], ['job_no'])
    op.create_foreign_key('equipment_time_job_no_fkey', 'equipment_time', 'jobs', ['job_no'], ['job_no'])
    op.create_foreign_key('additional_documents_job_no_fkey', 'additional_documents', 'jobs', ['job_no'], ['job_no'])
    op.create_foreign_key('witness_videos_job_no_fkey', 'witness_videos', 'jobs', ['job_no'], ['job_no'])
    op.create_foreign_key('witnesses_job_no_fkey', 'witnesses', 'jobs', ['job_no'], ['job_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraints that depend on uq_jobs_job_no
    op.drop_constraint('attorneys_job_no_fkey', 'attorneys', type_='foreignkey')
    op.drop_constraint('billings_job_no_fkey', 'billings', type_='foreignkey')
    op.drop_constraint('equipment_time_job_no_fkey', 'equipment_time', type_='foreignkey')
    op.drop_constraint('additional_documents_job_no_fkey', 'additional_documents', type_='foreignkey')
    op.drop_constraint('witness_videos_job_no_fkey', 'witness_videos', type_='foreignkey')
    op.drop_constraint('witnesses_job_no_fkey', 'witnesses', type_='foreignkey')
    
    # Drop and recreate unique constraint
    op.drop_constraint(op.f('uq_jobs_job_no'), 'jobs', type_='unique')
    op.create_unique_constraint(op.f('uq_jobs_job_no'), 'jobs', ['job_no'])
    
    # Recreate foreign key constraints
    op.create_foreign_key('attorneys_job_no_fkey', 'attorneys', 'jobs', ['job_no'], ['job_no'])
    op.create_foreign_key('billings_job_no_fkey', 'billings', 'jobs', ['job_no'], ['job_no'])
    op.create_foreign_key('equipment_time_job_no_fkey', 'equipment_time', 'jobs', ['job_no'], ['job_no'])
    op.create_foreign_key('additional_documents_job_no_fkey', 'additional_documents', 'jobs', ['job_no'], ['job_no'])
    op.create_foreign_key('witness_videos_job_no_fkey', 'witness_videos', 'jobs', ['job_no'], ['job_no'])
    op.create_foreign_key('witnesses_job_no_fkey', 'witnesses', 'jobs', ['job_no'], ['job_no'])
    op.drop_column('jobs', 'mark_is_done_equipment_time')
    op.drop_column('jobs', 'mark_is_done_billings')
    op.drop_column('jobs', 'mark_is_done_attorneys')
    op.drop_column('jobs', 'mark_is_done_witnesses')
    op.drop_column('jobs', 'mark_is_done_case')
    # Convert TIME back to VARCHAR for downgrade
    op.execute("""
        ALTER TABLE equipment_time 
        ALTER COLUMN time_after 
        TYPE VARCHAR(255) 
        USING CASE 
            WHEN time_after IS NULL THEN NULL
            ELSE time_after::TEXT
        END
    """)
    
    # Drop foreign key constraint first before modifying unique constraint
    op.drop_constraint('jobs_case_no_fkey', 'jobs', type_='foreignkey')
    # Drop and recreate unique constraint with original parameters
    op.drop_constraint(op.f('uq_cases_case_no'), 'cases', type_='unique')
    op.create_unique_constraint(op.f('uq_cases_case_no'), 'cases', ['case_no'])
    # Recreate foreign key constraint
    op.create_foreign_key('jobs_case_no_fkey', 'jobs', 'cases', ['case_no'], ['case_no'])
    # ### end Alembic commands ###
